// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FSProtocolHeaderPnt.proto

package custom.Hanwhatechwin.intersyslink.domain;

/**
 * Created by jhlee on 2017-09-19.
 */
public final class FSProtocolHeaderOuter {
    private FSProtocolHeaderOuter() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }
    public interface FSProtocolHeaderOrBuilder extends
            // @@protoc_insertion_point(interface_extends:FSProtocolHeader)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required string requestType = 1;</code>
         */
        boolean hasRequestType();
        /**
         * <code>required string requestType = 1;</code>
         */
        java.lang.String getRequestType();
        /**
         * <code>required string requestType = 1;</code>
         */
        com.google.protobuf.ByteString
        getRequestTypeBytes();

        /**
         * <code>required string dataType = 2;</code>
         */
        boolean hasDataType();
        /**
         * <code>required string dataType = 2;</code>
         */
        java.lang.String getDataType();
        /**
         * <code>required string dataType = 2;</code>
         */
        com.google.protobuf.ByteString
        getDataTypeBytes();

        /**
         * <code>required string encryptMode = 3;</code>
         */
        boolean hasEncryptMode();
        /**
         * <code>required string encryptMode = 3;</code>
         */
        java.lang.String getEncryptMode();
        /**
         * <code>required string encryptMode = 3;</code>
         */
        com.google.protobuf.ByteString
        getEncryptModeBytes();

        /**
         * <code>required string compressMode = 4;</code>
         */
        boolean hasCompressMode();
        /**
         * <code>required string compressMode = 4;</code>
         */
        java.lang.String getCompressMode();
        /**
         * <code>required string compressMode = 4;</code>
         */
        com.google.protobuf.ByteString
        getCompressModeBytes();

        /**
         * <code>required string agentType = 5;</code>
         */
        boolean hasAgentType();
        /**
         * <code>required string agentType = 5;</code>
         */
        java.lang.String getAgentType();
        /**
         * <code>required string agentType = 5;</code>
         */
        com.google.protobuf.ByteString
        getAgentTypeBytes();

        /**
         * <code>required string sourceId = 6;</code>
         */
        boolean hasSourceId();
        /**
         * <code>required string sourceId = 6;</code>
         */
        java.lang.String getSourceId();
        /**
         * <code>required string sourceId = 6;</code>
         */
        com.google.protobuf.ByteString
        getSourceIdBytes();

        /**
         * <code>required string targetId = 7;</code>
         */
        boolean hasTargetId();
        /**
         * <code>required string targetId = 7;</code>
         */
        java.lang.String getTargetId();
        /**
         * <code>required string targetId = 7;</code>
         */
        com.google.protobuf.ByteString
        getTargetIdBytes();

        /**
         * <code>optional string serverId = 8;</code>
         */
        boolean hasServerId();
        /**
         * <code>optional string serverId = 8;</code>
         */
        java.lang.String getServerId();
        /**
         * <code>optional string serverId = 8;</code>
         */
        com.google.protobuf.ByteString
        getServerIdBytes();

        /**
         * <code>required string realTime = 9;</code>
         */
        boolean hasRealTime();
        /**
         * <code>required string realTime = 9;</code>
         */
        java.lang.String getRealTime();
        /**
         * <code>required string realTime = 9;</code>
         */
        com.google.protobuf.ByteString
        getRealTimeBytes();

        /**
         * <code>required string heartbeat = 10;</code>
         */
        boolean hasHeartbeat();
        /**
         * <code>required string heartbeat = 10;</code>
         */
        java.lang.String getHeartbeat();
        /**
         * <code>required string heartbeat = 10;</code>
         */
        com.google.protobuf.ByteString
        getHeartbeatBytes();

        /**
         * <code>required string requestId = 11;</code>
         */
        boolean hasRequestId();
        /**
         * <code>required string requestId = 11;</code>
         */
        java.lang.String getRequestId();
        /**
         * <code>required string requestId = 11;</code>
         */
        com.google.protobuf.ByteString
        getRequestIdBytes();

        /**
         * <code>required bytes fsProtocolBodyBytes = 12;</code>
         */
        boolean hasFsProtocolBodyBytes();
        /**
         * <code>required bytes fsProtocolBodyBytes = 12;</code>
         */
        com.google.protobuf.ByteString getFsProtocolBodyBytes();
    }
    /**
     * Protobuf type {@code FSProtocolHeader}
     */
    public static final class FSProtocolHeader extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:FSProtocolHeader)
            FSProtocolHeaderOrBuilder {
        // Use FSProtocolHeader.newBuilder() to construct.
        private FSProtocolHeader(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }
        private FSProtocolHeader(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

        private static final FSProtocolHeader defaultInstance;
        public static FSProtocolHeader getDefaultInstance() {
            return defaultInstance;
        }

        public FSProtocolHeader getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private FSProtocolHeader(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            requestType_ = bs;
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            dataType_ = bs;
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            encryptMode_ = bs;
                            break;
                        }
                        case 34: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000008;
                            compressMode_ = bs;
                            break;
                        }
                        case 42: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000010;
                            agentType_ = bs;
                            break;
                        }
                        case 50: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000020;
                            sourceId_ = bs;
                            break;
                        }
                        case 58: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000040;
                            targetId_ = bs;
                            break;
                        }
                        case 66: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000080;
                            serverId_ = bs;
                            break;
                        }
                        case 74: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000100;
                            realTime_ = bs;
                            break;
                        }
                        case 82: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000200;
                            heartbeat_ = bs;
                            break;
                        }
                        case 90: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000400;
                            requestId_ = bs;
                            break;
                        }
                        case 98: {
                            bitField0_ |= 0x00000800;
                            fsProtocolBodyBytes_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.internal_static_FSProtocolHeader_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.internal_static_FSProtocolHeader_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader.class, custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader.Builder.class);
        }

        public static com.google.protobuf.Parser<FSProtocolHeader> PARSER =
                new com.google.protobuf.AbstractParser<FSProtocolHeader>() {
                    public FSProtocolHeader parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new FSProtocolHeader(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<FSProtocolHeader> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int REQUESTTYPE_FIELD_NUMBER = 1;
        private java.lang.Object requestType_;
        /**
         * <code>required string requestType = 1;</code>
         */
        public boolean hasRequestType() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string requestType = 1;</code>
         */
        public java.lang.String getRequestType() {
            java.lang.Object ref = requestType_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    requestType_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string requestType = 1;</code>
         */
        public com.google.protobuf.ByteString
        getRequestTypeBytes() {
            java.lang.Object ref = requestType_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                requestType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int DATATYPE_FIELD_NUMBER = 2;
        private java.lang.Object dataType_;
        /**
         * <code>required string dataType = 2;</code>
         */
        public boolean hasDataType() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string dataType = 2;</code>
         */
        public java.lang.String getDataType() {
            java.lang.Object ref = dataType_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    dataType_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string dataType = 2;</code>
         */
        public com.google.protobuf.ByteString
        getDataTypeBytes() {
            java.lang.Object ref = dataType_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                dataType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ENCRYPTMODE_FIELD_NUMBER = 3;
        private java.lang.Object encryptMode_;
        /**
         * <code>required string encryptMode = 3;</code>
         */
        public boolean hasEncryptMode() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required string encryptMode = 3;</code>
         */
        public java.lang.String getEncryptMode() {
            java.lang.Object ref = encryptMode_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    encryptMode_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string encryptMode = 3;</code>
         */
        public com.google.protobuf.ByteString
        getEncryptModeBytes() {
            java.lang.Object ref = encryptMode_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                encryptMode_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int COMPRESSMODE_FIELD_NUMBER = 4;
        private java.lang.Object compressMode_;
        /**
         * <code>required string compressMode = 4;</code>
         */
        public boolean hasCompressMode() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required string compressMode = 4;</code>
         */
        public java.lang.String getCompressMode() {
            java.lang.Object ref = compressMode_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    compressMode_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string compressMode = 4;</code>
         */
        public com.google.protobuf.ByteString
        getCompressModeBytes() {
            java.lang.Object ref = compressMode_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                compressMode_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int AGENTTYPE_FIELD_NUMBER = 5;
        private java.lang.Object agentType_;
        /**
         * <code>required string agentType = 5;</code>
         */
        public boolean hasAgentType() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>required string agentType = 5;</code>
         */
        public java.lang.String getAgentType() {
            java.lang.Object ref = agentType_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    agentType_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string agentType = 5;</code>
         */
        public com.google.protobuf.ByteString
        getAgentTypeBytes() {
            java.lang.Object ref = agentType_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                agentType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int SOURCEID_FIELD_NUMBER = 6;
        private java.lang.Object sourceId_;
        /**
         * <code>required string sourceId = 6;</code>
         */
        public boolean hasSourceId() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>required string sourceId = 6;</code>
         */
        public java.lang.String getSourceId() {
            java.lang.Object ref = sourceId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    sourceId_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string sourceId = 6;</code>
         */
        public com.google.protobuf.ByteString
        getSourceIdBytes() {
            java.lang.Object ref = sourceId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                sourceId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int TARGETID_FIELD_NUMBER = 7;
        private java.lang.Object targetId_;
        /**
         * <code>required string targetId = 7;</code>
         */
        public boolean hasTargetId() {
            return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>required string targetId = 7;</code>
         */
        public java.lang.String getTargetId() {
            java.lang.Object ref = targetId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    targetId_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string targetId = 7;</code>
         */
        public com.google.protobuf.ByteString
        getTargetIdBytes() {
            java.lang.Object ref = targetId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                targetId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int SERVERID_FIELD_NUMBER = 8;
        private java.lang.Object serverId_;
        /**
         * <code>optional string serverId = 8;</code>
         */
        public boolean hasServerId() {
            return ((bitField0_ & 0x00000080) == 0x00000080);
        }
        /**
         * <code>optional string serverId = 8;</code>
         */
        public java.lang.String getServerId() {
            java.lang.Object ref = serverId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    serverId_ = s;
                }
                return s;
            }
        }
        /**
         * <code>optional string serverId = 8;</code>
         */
        public com.google.protobuf.ByteString
        getServerIdBytes() {
            java.lang.Object ref = serverId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                serverId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int REALTIME_FIELD_NUMBER = 9;
        private java.lang.Object realTime_;
        /**
         * <code>required string realTime = 9;</code>
         */
        public boolean hasRealTime() {
            return ((bitField0_ & 0x00000100) == 0x00000100);
        }
        /**
         * <code>required string realTime = 9;</code>
         */
        public java.lang.String getRealTime() {
            java.lang.Object ref = realTime_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    realTime_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string realTime = 9;</code>
         */
        public com.google.protobuf.ByteString
        getRealTimeBytes() {
            java.lang.Object ref = realTime_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                realTime_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int HEARTBEAT_FIELD_NUMBER = 10;
        private java.lang.Object heartbeat_;
        /**
         * <code>required string heartbeat = 10;</code>
         */
        public boolean hasHeartbeat() {
            return ((bitField0_ & 0x00000200) == 0x00000200);
        }
        /**
         * <code>required string heartbeat = 10;</code>
         */
        public java.lang.String getHeartbeat() {
            java.lang.Object ref = heartbeat_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    heartbeat_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string heartbeat = 10;</code>
         */
        public com.google.protobuf.ByteString
        getHeartbeatBytes() {
            java.lang.Object ref = heartbeat_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                heartbeat_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int REQUESTID_FIELD_NUMBER = 11;
        private java.lang.Object requestId_;
        /**
         * <code>required string requestId = 11;</code>
         */
        public boolean hasRequestId() {
            return ((bitField0_ & 0x00000400) == 0x00000400);
        }
        /**
         * <code>required string requestId = 11;</code>
         */
        public java.lang.String getRequestId() {
            java.lang.Object ref = requestId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    requestId_ = s;
                }
                return s;
            }
        }
        /**
         * <code>required string requestId = 11;</code>
         */
        public com.google.protobuf.ByteString
        getRequestIdBytes() {
            java.lang.Object ref = requestId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                requestId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int FSPROTOCOLBODYBYTES_FIELD_NUMBER = 12;
        private com.google.protobuf.ByteString fsProtocolBodyBytes_;
        /**
         * <code>required bytes fsProtocolBodyBytes = 12;</code>
         */
        public boolean hasFsProtocolBodyBytes() {
            return ((bitField0_ & 0x00000800) == 0x00000800);
        }
        /**
         * <code>required bytes fsProtocolBodyBytes = 12;</code>
         */
        public com.google.protobuf.ByteString getFsProtocolBodyBytes() {
            return fsProtocolBodyBytes_;
        }

        private void initFields() {
            requestType_ = "";
            dataType_ = "";
            encryptMode_ = "";
            compressMode_ = "";
            agentType_ = "";
            sourceId_ = "";
            targetId_ = "";
            serverId_ = "";
            realTime_ = "";
            heartbeat_ = "";
            requestId_ = "";
            fsProtocolBodyBytes_ = com.google.protobuf.ByteString.EMPTY;
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasRequestType()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasDataType()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasEncryptMode()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasCompressMode()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasAgentType()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasSourceId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasTargetId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasRealTime()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasHeartbeat()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasRequestId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasFsProtocolBodyBytes()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getRequestTypeBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getDataTypeBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getEncryptModeBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeBytes(4, getCompressModeBytes());
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeBytes(5, getAgentTypeBytes());
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                output.writeBytes(6, getSourceIdBytes());
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                output.writeBytes(7, getTargetIdBytes());
            }
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
                output.writeBytes(8, getServerIdBytes());
            }
            if (((bitField0_ & 0x00000100) == 0x00000100)) {
                output.writeBytes(9, getRealTimeBytes());
            }
            if (((bitField0_ & 0x00000200) == 0x00000200)) {
                output.writeBytes(10, getHeartbeatBytes());
            }
            if (((bitField0_ & 0x00000400) == 0x00000400)) {
                output.writeBytes(11, getRequestIdBytes());
            }
            if (((bitField0_ & 0x00000800) == 0x00000800)) {
                output.writeBytes(12, fsProtocolBodyBytes_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getRequestTypeBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getDataTypeBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, getEncryptModeBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, getCompressModeBytes());
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(5, getAgentTypeBytes());
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(6, getSourceIdBytes());
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(7, getTargetIdBytes());
            }
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(8, getServerIdBytes());
            }
            if (((bitField0_ & 0x00000100) == 0x00000100)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(9, getRealTimeBytes());
            }
            if (((bitField0_ & 0x00000200) == 0x00000200)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(10, getHeartbeatBytes());
            }
            if (((bitField0_ & 0x00000400) == 0x00000400)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(11, getRequestIdBytes());
            }
            if (((bitField0_ & 0x00000800) == 0x00000800)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(12, fsProtocolBodyBytes_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }
        public static custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }
        public static custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }
        public static custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }
        public static custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code FSProtocolHeader}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:FSProtocolHeader)
                custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeaderOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.internal_static_FSProtocolHeader_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.internal_static_FSProtocolHeader_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader.class, custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader.Builder.class);
            }

            // Construct using custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }
            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                requestType_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                dataType_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                encryptMode_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                compressMode_ = "";
                bitField0_ = (bitField0_ & ~0x00000008);
                agentType_ = "";
                bitField0_ = (bitField0_ & ~0x00000010);
                sourceId_ = "";
                bitField0_ = (bitField0_ & ~0x00000020);
                targetId_ = "";
                bitField0_ = (bitField0_ & ~0x00000040);
                serverId_ = "";
                bitField0_ = (bitField0_ & ~0x00000080);
                realTime_ = "";
                bitField0_ = (bitField0_ & ~0x00000100);
                heartbeat_ = "";
                bitField0_ = (bitField0_ & ~0x00000200);
                requestId_ = "";
                bitField0_ = (bitField0_ & ~0x00000400);
                fsProtocolBodyBytes_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000800);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.internal_static_FSProtocolHeader_descriptor;
            }

            public custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader getDefaultInstanceForType() {
                return custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader.getDefaultInstance();
            }

            public custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader build() {
                custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader buildPartial() {
                custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader result = new custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.requestType_ = requestType_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.dataType_ = dataType_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.encryptMode_ = encryptMode_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.compressMode_ = compressMode_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.agentType_ = agentType_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.sourceId_ = sourceId_;
                if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
                    to_bitField0_ |= 0x00000040;
                }
                result.targetId_ = targetId_;
                if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
                    to_bitField0_ |= 0x00000080;
                }
                result.serverId_ = serverId_;
                if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
                    to_bitField0_ |= 0x00000100;
                }
                result.realTime_ = realTime_;
                if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
                    to_bitField0_ |= 0x00000200;
                }
                result.heartbeat_ = heartbeat_;
                if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
                    to_bitField0_ |= 0x00000400;
                }
                result.requestId_ = requestId_;
                if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
                    to_bitField0_ |= 0x00000800;
                }
                result.fsProtocolBodyBytes_ = fsProtocolBodyBytes_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader) {
                    return mergeFrom((custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader other) {
                if (other == custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader.getDefaultInstance()) return this;
                if (other.hasRequestType()) {
                    bitField0_ |= 0x00000001;
                    requestType_ = other.requestType_;
                    onChanged();
                }
                if (other.hasDataType()) {
                    bitField0_ |= 0x00000002;
                    dataType_ = other.dataType_;
                    onChanged();
                }
                if (other.hasEncryptMode()) {
                    bitField0_ |= 0x00000004;
                    encryptMode_ = other.encryptMode_;
                    onChanged();
                }
                if (other.hasCompressMode()) {
                    bitField0_ |= 0x00000008;
                    compressMode_ = other.compressMode_;
                    onChanged();
                }
                if (other.hasAgentType()) {
                    bitField0_ |= 0x00000010;
                    agentType_ = other.agentType_;
                    onChanged();
                }
                if (other.hasSourceId()) {
                    bitField0_ |= 0x00000020;
                    sourceId_ = other.sourceId_;
                    onChanged();
                }
                if (other.hasTargetId()) {
                    bitField0_ |= 0x00000040;
                    targetId_ = other.targetId_;
                    onChanged();
                }
                if (other.hasServerId()) {
                    bitField0_ |= 0x00000080;
                    serverId_ = other.serverId_;
                    onChanged();
                }
                if (other.hasRealTime()) {
                    bitField0_ |= 0x00000100;
                    realTime_ = other.realTime_;
                    onChanged();
                }
                if (other.hasHeartbeat()) {
                    bitField0_ |= 0x00000200;
                    heartbeat_ = other.heartbeat_;
                    onChanged();
                }
                if (other.hasRequestId()) {
                    bitField0_ |= 0x00000400;
                    requestId_ = other.requestId_;
                    onChanged();
                }
                if (other.hasFsProtocolBodyBytes()) {
                    setFsProtocolBodyBytes(other.getFsProtocolBodyBytes());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasRequestType()) {

                    return false;
                }
                if (!hasDataType()) {

                    return false;
                }
                if (!hasEncryptMode()) {

                    return false;
                }
                if (!hasCompressMode()) {

                    return false;
                }
                if (!hasAgentType()) {

                    return false;
                }
                if (!hasSourceId()) {

                    return false;
                }
                if (!hasTargetId()) {

                    return false;
                }
                if (!hasRealTime()) {

                    return false;
                }
                if (!hasHeartbeat()) {

                    return false;
                }
                if (!hasRequestId()) {

                    return false;
                }
                if (!hasFsProtocolBodyBytes()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (custom.Hanwhatechwin.intersyslink.domain.FSProtocolHeaderOuter.FSProtocolHeader) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.lang.Object requestType_ = "";
            /**
             * <code>required string requestType = 1;</code>
             */
            public boolean hasRequestType() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            /**
             * <code>required string requestType = 1;</code>
             */
            public java.lang.String getRequestType() {
                java.lang.Object ref = requestType_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        requestType_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string requestType = 1;</code>
             */
            public com.google.protobuf.ByteString
            getRequestTypeBytes() {
                java.lang.Object ref = requestType_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    requestType_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string requestType = 1;</code>
             */
            public Builder setRequestType(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                requestType_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string requestType = 1;</code>
             */
            public Builder clearRequestType() {
                bitField0_ = (bitField0_ & ~0x00000001);
                requestType_ = getDefaultInstance().getRequestType();
                onChanged();
                return this;
            }
            /**
             * <code>required string requestType = 1;</code>
             */
            public Builder setRequestTypeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                requestType_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object dataType_ = "";
            /**
             * <code>required string dataType = 2;</code>
             */
            public boolean hasDataType() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            /**
             * <code>required string dataType = 2;</code>
             */
            public java.lang.String getDataType() {
                java.lang.Object ref = dataType_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        dataType_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string dataType = 2;</code>
             */
            public com.google.protobuf.ByteString
            getDataTypeBytes() {
                java.lang.Object ref = dataType_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    dataType_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string dataType = 2;</code>
             */
            public Builder setDataType(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                dataType_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string dataType = 2;</code>
             */
            public Builder clearDataType() {
                bitField0_ = (bitField0_ & ~0x00000002);
                dataType_ = getDefaultInstance().getDataType();
                onChanged();
                return this;
            }
            /**
             * <code>required string dataType = 2;</code>
             */
            public Builder setDataTypeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                dataType_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object encryptMode_ = "";
            /**
             * <code>required string encryptMode = 3;</code>
             */
            public boolean hasEncryptMode() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }
            /**
             * <code>required string encryptMode = 3;</code>
             */
            public java.lang.String getEncryptMode() {
                java.lang.Object ref = encryptMode_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        encryptMode_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string encryptMode = 3;</code>
             */
            public com.google.protobuf.ByteString
            getEncryptModeBytes() {
                java.lang.Object ref = encryptMode_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    encryptMode_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string encryptMode = 3;</code>
             */
            public Builder setEncryptMode(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                encryptMode_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string encryptMode = 3;</code>
             */
            public Builder clearEncryptMode() {
                bitField0_ = (bitField0_ & ~0x00000004);
                encryptMode_ = getDefaultInstance().getEncryptMode();
                onChanged();
                return this;
            }
            /**
             * <code>required string encryptMode = 3;</code>
             */
            public Builder setEncryptModeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                encryptMode_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object compressMode_ = "";
            /**
             * <code>required string compressMode = 4;</code>
             */
            public boolean hasCompressMode() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }
            /**
             * <code>required string compressMode = 4;</code>
             */
            public java.lang.String getCompressMode() {
                java.lang.Object ref = compressMode_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        compressMode_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string compressMode = 4;</code>
             */
            public com.google.protobuf.ByteString
            getCompressModeBytes() {
                java.lang.Object ref = compressMode_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    compressMode_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string compressMode = 4;</code>
             */
            public Builder setCompressMode(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                compressMode_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string compressMode = 4;</code>
             */
            public Builder clearCompressMode() {
                bitField0_ = (bitField0_ & ~0x00000008);
                compressMode_ = getDefaultInstance().getCompressMode();
                onChanged();
                return this;
            }
            /**
             * <code>required string compressMode = 4;</code>
             */
            public Builder setCompressModeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                compressMode_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object agentType_ = "";
            /**
             * <code>required string agentType = 5;</code>
             */
            public boolean hasAgentType() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }
            /**
             * <code>required string agentType = 5;</code>
             */
            public java.lang.String getAgentType() {
                java.lang.Object ref = agentType_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        agentType_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string agentType = 5;</code>
             */
            public com.google.protobuf.ByteString
            getAgentTypeBytes() {
                java.lang.Object ref = agentType_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    agentType_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string agentType = 5;</code>
             */
            public Builder setAgentType(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                agentType_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string agentType = 5;</code>
             */
            public Builder clearAgentType() {
                bitField0_ = (bitField0_ & ~0x00000010);
                agentType_ = getDefaultInstance().getAgentType();
                onChanged();
                return this;
            }
            /**
             * <code>required string agentType = 5;</code>
             */
            public Builder setAgentTypeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                agentType_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object sourceId_ = "";
            /**
             * <code>required string sourceId = 6;</code>
             */
            public boolean hasSourceId() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }
            /**
             * <code>required string sourceId = 6;</code>
             */
            public java.lang.String getSourceId() {
                java.lang.Object ref = sourceId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        sourceId_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string sourceId = 6;</code>
             */
            public com.google.protobuf.ByteString
            getSourceIdBytes() {
                java.lang.Object ref = sourceId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    sourceId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string sourceId = 6;</code>
             */
            public Builder setSourceId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000020;
                sourceId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string sourceId = 6;</code>
             */
            public Builder clearSourceId() {
                bitField0_ = (bitField0_ & ~0x00000020);
                sourceId_ = getDefaultInstance().getSourceId();
                onChanged();
                return this;
            }
            /**
             * <code>required string sourceId = 6;</code>
             */
            public Builder setSourceIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000020;
                sourceId_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object targetId_ = "";
            /**
             * <code>required string targetId = 7;</code>
             */
            public boolean hasTargetId() {
                return ((bitField0_ & 0x00000040) == 0x00000040);
            }
            /**
             * <code>required string targetId = 7;</code>
             */
            public java.lang.String getTargetId() {
                java.lang.Object ref = targetId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        targetId_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string targetId = 7;</code>
             */
            public com.google.protobuf.ByteString
            getTargetIdBytes() {
                java.lang.Object ref = targetId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    targetId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string targetId = 7;</code>
             */
            public Builder setTargetId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000040;
                targetId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string targetId = 7;</code>
             */
            public Builder clearTargetId() {
                bitField0_ = (bitField0_ & ~0x00000040);
                targetId_ = getDefaultInstance().getTargetId();
                onChanged();
                return this;
            }
            /**
             * <code>required string targetId = 7;</code>
             */
            public Builder setTargetIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000040;
                targetId_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object serverId_ = "";
            /**
             * <code>optional string serverId = 8;</code>
             */
            public boolean hasServerId() {
                return ((bitField0_ & 0x00000080) == 0x00000080);
            }
            /**
             * <code>optional string serverId = 8;</code>
             */
            public java.lang.String getServerId() {
                java.lang.Object ref = serverId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        serverId_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>optional string serverId = 8;</code>
             */
            public com.google.protobuf.ByteString
            getServerIdBytes() {
                java.lang.Object ref = serverId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    serverId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>optional string serverId = 8;</code>
             */
            public Builder setServerId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000080;
                serverId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>optional string serverId = 8;</code>
             */
            public Builder clearServerId() {
                bitField0_ = (bitField0_ & ~0x00000080);
                serverId_ = getDefaultInstance().getServerId();
                onChanged();
                return this;
            }
            /**
             * <code>optional string serverId = 8;</code>
             */
            public Builder setServerIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000080;
                serverId_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object realTime_ = "";
            /**
             * <code>required string realTime = 9;</code>
             */
            public boolean hasRealTime() {
                return ((bitField0_ & 0x00000100) == 0x00000100);
            }
            /**
             * <code>required string realTime = 9;</code>
             */
            public java.lang.String getRealTime() {
                java.lang.Object ref = realTime_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        realTime_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string realTime = 9;</code>
             */
            public com.google.protobuf.ByteString
            getRealTimeBytes() {
                java.lang.Object ref = realTime_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    realTime_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string realTime = 9;</code>
             */
            public Builder setRealTime(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000100;
                realTime_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string realTime = 9;</code>
             */
            public Builder clearRealTime() {
                bitField0_ = (bitField0_ & ~0x00000100);
                realTime_ = getDefaultInstance().getRealTime();
                onChanged();
                return this;
            }
            /**
             * <code>required string realTime = 9;</code>
             */
            public Builder setRealTimeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000100;
                realTime_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object heartbeat_ = "";
            /**
             * <code>required string heartbeat = 10;</code>
             */
            public boolean hasHeartbeat() {
                return ((bitField0_ & 0x00000200) == 0x00000200);
            }
            /**
             * <code>required string heartbeat = 10;</code>
             */
            public java.lang.String getHeartbeat() {
                java.lang.Object ref = heartbeat_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        heartbeat_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string heartbeat = 10;</code>
             */
            public com.google.protobuf.ByteString
            getHeartbeatBytes() {
                java.lang.Object ref = heartbeat_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    heartbeat_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string heartbeat = 10;</code>
             */
            public Builder setHeartbeat(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000200;
                heartbeat_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string heartbeat = 10;</code>
             */
            public Builder clearHeartbeat() {
                bitField0_ = (bitField0_ & ~0x00000200);
                heartbeat_ = getDefaultInstance().getHeartbeat();
                onChanged();
                return this;
            }
            /**
             * <code>required string heartbeat = 10;</code>
             */
            public Builder setHeartbeatBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000200;
                heartbeat_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object requestId_ = "";
            /**
             * <code>required string requestId = 11;</code>
             */
            public boolean hasRequestId() {
                return ((bitField0_ & 0x00000400) == 0x00000400);
            }
            /**
             * <code>required string requestId = 11;</code>
             */
            public java.lang.String getRequestId() {
                java.lang.Object ref = requestId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        requestId_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>required string requestId = 11;</code>
             */
            public com.google.protobuf.ByteString
            getRequestIdBytes() {
                java.lang.Object ref = requestId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    requestId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>required string requestId = 11;</code>
             */
            public Builder setRequestId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000400;
                requestId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required string requestId = 11;</code>
             */
            public Builder clearRequestId() {
                bitField0_ = (bitField0_ & ~0x00000400);
                requestId_ = getDefaultInstance().getRequestId();
                onChanged();
                return this;
            }
            /**
             * <code>required string requestId = 11;</code>
             */
            public Builder setRequestIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000400;
                requestId_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString fsProtocolBodyBytes_ = com.google.protobuf.ByteString.EMPTY;
            /**
             * <code>required bytes fsProtocolBodyBytes = 12;</code>
             */
            public boolean hasFsProtocolBodyBytes() {
                return ((bitField0_ & 0x00000800) == 0x00000800);
            }
            /**
             * <code>required bytes fsProtocolBodyBytes = 12;</code>
             */
            public com.google.protobuf.ByteString getFsProtocolBodyBytes() {
                return fsProtocolBodyBytes_;
            }
            /**
             * <code>required bytes fsProtocolBodyBytes = 12;</code>
             */
            public Builder setFsProtocolBodyBytes(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000800;
                fsProtocolBodyBytes_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>required bytes fsProtocolBodyBytes = 12;</code>
             */
            public Builder clearFsProtocolBodyBytes() {
                bitField0_ = (bitField0_ & ~0x00000800);
                fsProtocolBodyBytes_ = getDefaultInstance().getFsProtocolBodyBytes();
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:FSProtocolHeader)
        }

        static {
            defaultInstance = new FSProtocolHeader(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:FSProtocolHeader)
    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_FSProtocolHeader_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_FSProtocolHeader_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\031FSProtocolHeaderPnt.proto\"\202\002\n\020FSProtoc" +
                        "olHeader\022\023\n\013requestType\030\001 \002(\t\022\020\n\010dataTyp" +
                        "e\030\002 \002(\t\022\023\n\013encryptMode\030\003 \002(\t\022\024\n\014compress" +
                        "Mode\030\004 \002(\t\022\021\n\tagentType\030\005 \002(\t\022\020\n\010sourceI" +
                        "d\030\006 \002(\t\022\020\n\010targetId\030\007 \002(\t\022\020\n\010serverId\030\010 " +
                        "\001(\t\022\020\n\010realTime\030\t \002(\t\022\021\n\theartbeat\030\n \002(\t" +
                        "\022\021\n\trequestId\030\013 \002(\t\022\033\n\023fsProtocolBodyByt" +
                        "es\030\014 \002(\014BC\n(custom.Hanwhatechwin.intersy" +
                        "slink.domainB\025FSProtocolHeaderOuterH\001"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_FSProtocolHeader_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_FSProtocolHeader_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_FSProtocolHeader_descriptor,
                new java.lang.String[] { "RequestType", "DataType", "EncryptMode", "CompressMode", "AgentType", "SourceId", "TargetId", "ServerId", "RealTime", "Heartbeat", "RequestId", "FsProtocolBodyBytes", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}

